#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Check if the branch name matches the Gitflow pattern
if ! echo "$branch_name" | grep -qE '^((main|dev)|(feature|hotfix|release|bugfix|experimental)\/[a-z0-9._-]+)$'; then
  echo "Error: Branch name '$branch_name' does not follow the Gitflow pattern."
  exit 1 # The branch name is invalid, exit with failure
fi

# Check if the branch exists on the remote
if git show-ref --verify --quiet refs/remotes/origin/$branch_name; then
  # Get the names of all files that have changed in the commits that are present locally but not yet pushed to the remote repository
  changed_files=$(git diff --name-only origin/$branch_name HEAD)
else
  # Get the names of all files that have changed since the branch was created
  changed_files=$(git diff --name-only $(git merge-base HEAD dev) HEAD)
fi


docs="\.md|\.mdx|\.tsx|\.jsx"
if echo "$changed_files" | grep -qE "(\.ts|\.js|$docs|package\.json|package-lock\.yaml)$"; then
  if echo "$changed_files" | grep -qE '(\.md|\.mdx|\.jsx|\.tsx)$'; then
    cd docs && pnpm build
  fi
fi
