name: Documentation Action

on:
  push:
    branches: [ main ]
    tags:
      # Match any docs tag (e.g docs-v1.0.0)
      - 'docs-v*'
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to coolify'
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/docs-v')}}

jobs:
  build:
    name: Build Docs
    uses: Streetless/actions/.github/workflows/docs.yml@main
    secrets: inherit
    with:
      deploy: ${{ github.event.inputs.deploy || true }}
      default-branch: main
