name: Release Please Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    name: Release Please
    uses: Streetless/actions/.github/workflows/release-please.yml@main
    secrets: inherit
    with:
      target-branch: main
      use-root-gitflow: false
